# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import faces.models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_field',
            field=models.FileField(upload_to=faces.models.generate_filename),
        ),
    ]
